### ISSUE TITLE
launching of Intellij fails with No such file or directory error.

### ISSUE THREAD

**Issue by ravicm2** [devonfw/ide#399]
### Expected behavior

As a developer, I want to use intellij for the faster development which increases my productivity.

### Actual behavior
I followed the instructions given in devonfw.com to install the devon ide version 3.3.1 and tried to launch the intellij as guided in the document . After successful downloading and extracting of intellij, the devon ide fails to launch it with the below error.

`/c/projects/devon/devonfw-ide-scripts-3.3.1/scripts/command/intellij: line 72: /c/projects/devon/devonfw-ide-scripts-3.3.1/software/intellij/idea: No such file or directory`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  Open devon CMD in the devon ide downloaded folder
2.  Type `devon intellij setup`
3.  After successful download it will say an error `unable to execute -v idea`
4.  Now, Type `devon intellij run or start` to launch the downloaded intellij 

Now it will throw the error menntioned.

### Affected version:

* Devon-ide:3.3.1 and its same for 3.2.1 also.
* OS: Windows
* Browser: Chrome

**Comment by hohwille** [comment]
IMHO this issue is a "duplicate" or at least what is already fixed with PR #402
In case I am mistaken, please let me know.

**Comment by hohwille** [comment]
Fixed with PR #402

**Comment by ravicm2** [comment]
Hi @hohwille , i just tried with the new release of 2020.04.001 but unfortunately  still the error remains same .

**Comment by ravicm2** [comment]
i checked with the latest devon-ide(2020.04.001), unfortunately still the issue exists

**Comment by hohwille** [comment]
OK, I tried it on my Windows VM and indeed it is not yet working. However, now there is another bug. The executable is not named `idea` but `idea64` (with `.exe` extension). 

@ravicm2 You could help me a lot and save a lot of time if you would include such details in the issue comments. I am working on MacOS and testing on Windows requires extra time while time is my rares resource.

I will fix this asap.

**Comment by hohwille** [comment]
Closing after merge of PR #423

**Comment by ravicm2** [comment]
> OK, I tried it on my Windows VM and indeed it is not yet working. However, now there is another bug. The executable is not named `idea` but `idea64` (with `.exe` extension). 
> 
> @ravicm2 You could help me a lot and save a lot of time if you would include such details in the issue comments. I am working on MacOS and testing on Windows requires extra time while time is my rares resource.
> 
> I will fix this asap.

Ok thank you so much and I didn't know the actual error . Just saw this error on the cmd . 
Will make sure to put full details in the next tickets if anything comes.
